name: Deploy

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Build porfolio-app
        run: |
          npm ci
          npm run build
      - name: Deploy to main
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GTIHUB_TOKEN}}
          publish_dir: ./build
